"""comments2

Revision ID: 1581e34ae5bb
Revises: 
Create Date: 2017-12-03 00:55:41.937033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1581e34ae5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coursecomment', sa.Column('childrencount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coursecomment', 'childrencount')
    # ### end Alembic commands ###
