"""courseposts

Revision ID: 870508b9cbb3
Revises: 
Create Date: 2018-01-08 16:07:22.610098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870508b9cbb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(u'fk_users_role_id_roles', type_='foreignkey')
        batch_op.drop_column('email')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_foreign_key(u'fk_users_role_id_roles', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
