"""courseposts

Revision ID: c34bae7d6cad
Revises: c9f81df5b4e5
Create Date: 2018-01-08 15:54:36.445758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34bae7d6cad'
down_revision = 'c9f81df5b4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_school_collegename'), ['collegename'])

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_topics_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_topics_name'), type_='unique')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_school_collegename'), type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'topics', ['course_id'], ['id'])

    # ### end Alembic commands ###
