"""school official name removed

Revision ID: c9f81df5b4e5
Revises: 36f96c3a7fc6
Create Date: 2017-12-04 23:38:20.172384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f81df5b4e5'
down_revision = '36f96c3a7fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'school', ['collegename'])
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'school', type_='unique')
    # ### end Alembic commands ###
    pass
