"""qq_openid

Revision ID: e7669c93646a
Revises: 0120d1b0a877
Create Date: 2018-01-22 19:05:10.905752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7669c93646a'
down_revision = '0120d1b0a877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qq_openid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_qq_openid'), ['qq_openid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_qq_openid'))
        batch_op.drop_column('qq_openid')

    # ### end Alembic commands ###
