"""courseposts

Revision ID: f53b38898bf8
Revises: c9f81df5b4e5
Create Date: 2018-01-07 14:29:18.515817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53b38898bf8'
down_revision = 'c9f81df5b4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'])
    op.add_column('posts', sa.Column('belong_to_course', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'course_id')
    op.drop_column('posts', 'belong_to_course')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
